### ISSUE TITLE
Datepair's timepicker allows invalid input

### ISSUE THREAD

**Issue by abarbaspring** [jonthornton/Datepair.js#39] opened 2015-04-10 13:37 UTC
Hi, I'm having a problem with the timepicker in the Datepair.

Actually, it is allowing invalid input such as 'kdgjlsklfdj' and this input is automatically converted into 00:00 hrs. I need that the timepicker does not allow such input, maybe invalidating the control.

Besides, once the invalid input is typed in the first timepicker, the datepair stops updating the second timepicker with the delta, even I put a valid time in the first timepicker.

**Comment by jonthornton** [comment] 2015-04-10 14:46
I'm not able to reproduce this problem. Can you post a jsFiddle and step by step instructions to demonstrate the glitch?

**Comment by abarbaspring** [comment] 2015-04-10 22:39
Hi, Jonh.

In fact, I have used your example from http://jonthornton.github.io/Datepair.js/

But I also put it on https://jsfiddle.net/mwmm3xkn/

So, let me explain the steps to reproduce the problem:
1) Select a date on the first date field. The second date field will be filled automatically.
2) Select an hour on the first time field. The second time field will be filled automatically.
3) (Error 1) Type adsfasdgkljl on the first time field. After losing focus the field is not invalidated.
4) (Error 2) If I select any time in the first time field now, the second time field is not updated anymore.

**Comment by jonthornton** [comment] 2015-04-11 14:40
Error 1 is expected behavior - see comment on https://github.com/jonthornton/jquery-timepicker/issues/383.

Error 2 was a bug and should be fixed now. Thanks for posting a bug report!

**Closed by jonthornton** 2015-04-11 14:40 UTC
Labels: not confirmed
